/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fanta

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class PrimeTest {

    @Test
    fun `filtering primes in sequence`() {
        val seq = sequenceOf(1, 2, 3, 4, 5, 6, 7, 8, 9).primes()
        assertEquals(4, seq.size, "Primality test failed")
        assertEquals(2, seq[0], "Primality test failed")
        assertEquals(3, seq[1], "Primality test failed")
        assertEquals(5, seq[2], "Primality test failed")
        assertEquals(7, seq[3], "Primality test failed")
    }

    @Test
    fun `filtering primes in array`() {
        val arr = arrayOf(1, 2, 3, 4, 5, 6, 7, 8, 9).primes()
        assertEquals(4, arr.size, "Primality test failed")
        assertEquals(2, arr[0], "Primality test failed")
        assertEquals(3, arr[1], "Primality test failed")
        assertEquals(5, arr[2], "Primality test failed")
        assertEquals(7, arr[3], "Primality test failed")
    }
}
