/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fanta

import org.apache.commons.math3.primes.Primes

fun Sequence<Int>.primes() = filter { i -> Primes.isPrime(i) }.toList()
fun Array<Int>.primes() = filter { i -> Primes.isPrime(i) }.toIntArray()
